# Basic config
baseURL = "https://ivoverhoeven.com"
theme = ["hugo-bearcub", "hugo-simplecite"]
copyright = "This work is licensed as CC BY 4.0"
defaultContentLanguage = "en"
canonifyURLs = true

[sitemap]
changefreq = "weekly"
priority = 0.5

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$']]
inline = [['$', '$']]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
 unsafe = true

[markup.highlight]
lineNos = true
lineNumbersInTable = false
# This allows Bear Cub to use a variation of Dracula that is more accessible
# to people with poor eyesight. For more information about color contrast
# and accessibility, see https://web.dev/color-and-contrast-accessibility/
noClasses = false

[markup.tableOfContents]
startLevel = 2
endLevel = 3
ordered = true

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
[languages.en]
title = "Ivo Verhoeven"
languageName = "en-US 🇺🇸"
LanguageCode = "en-US"
contentDir = "content"
[languages.en.params]
madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"

[params]
# The description of your website
description = "Ivo Verhoeven's personal page"

# The path to your favicon
favicon = "favicon.ico"

# These images will show up when services want to generate a preview of a link
# to your site. Ignored if `generateSocialCard = true`. For more information
# about previews, see https://gohugo.io/templates/internal#twitter-cards and
# https://gohugo.io/templates/internal#open-graph
images = ["share_personal.webp"]

# This title is used as the site_name on the Hugo's internal opengraph
# structured data template
title = "Bear Cub"

# Dates are displayed following the format below. For more information about
# formatting, see https://gohugo.io/functions/format/
dateFormat = "2006-01-02"

# If your blog is multilingual but you haven't translated a page, this theme
# will create a disabled link. By setting `hideUntranslated` to true, you can
# have the theme simply not show any link
hideUntranslated = false

# (EXPERIMENTAL) This theme has two options for its CSS styles: "original" and
# "herman". The former is what you see on Bear Cub's demo (an optimized
# version of Hugo Bear Blog), while the latter has a more modern look based on
# Herman Martinus's version of the Blogster Minimal theme for Astro.
themeStyle = "herman"

# (EXPERIMENTAL) This theme is capable of dynamically generating social cards
# for posts that don't have `images` defined in their front matter; By setting
# `generateSocialCard` to false, you can prevent this behavior. For more
# information see layouts/partials/social_card.html
generateSocialCard = false

# Custom CSS files
customCss = [
  "css/main.css",
  "css/color.css",
  "css/syntax.css",
  # "css/sidenote.css",
  "css/icons.css",
  "css/toc.css",
  "css/notice.css",
  "css/outgoing_links.css",
]

# Enable MathJax
math = false

# Enable ToC
tableOfContents = false

[params.social]

# Author metadata. This is mostly used for the RSS feed of your site, but the
# email is also added to the footer of each post. You can hide the "reply to"
# link by using a `hideReply` param in front matter.
[params.author]
name = "Ivo Verhoeven" # Your name as shown in the RSS feed metadata
#email = "i.o.verhoeven@uva.nl" # Added to the footer so readers can reply to posts

[module]
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/bootstrap'

[[module.imports]]
path = 'github.com/hugomods/icons/vendors/simple-icons'
