[project]
authors = ["ioverho <ioverho@mailbox.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ioverho.github.io"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.7,<4"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.5,<9"
pixi-kernel = ">=0.5.0,<0.6"
numpy = ">=2.1.2,<3"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
statsmodels = ">=0.14.4,<0.15"
ruff = ">=0.6.9,<0.7"
jaxtyping = ">=0.2.34,<0.3"
